#	only superusers can read, create, edit or destroy
#	this will be the update
#	THESE CANNOT BE EMPTY
superuser_resources:
  - birth_datum_updates 
  - icf_master_tracker_updates 
  - screening_datum_updates 

#	only admins and above can read, create, edit or destroy
administrator_resources:
  - address_types 
  - birth_data
  - birth_records 
  - contexts 
  - data_sources
  - diagnoses 
  - document_types 
  - document_versions 
  - follow_up_types
  - hospitals 
  - icf_master_ids 
  - icf_master_trackers
  - ineligible_reasons
  - instruments 
  - instrument_types 
  - instrument_versions
  - interview_methods 
  - interview_outcomes 
  - languages
  - odms_exceptions 
  - operational_event_types 
  - organizations
  - people 
  - phone_types 
  - project_outcomes 
  - races 
  - refusal_reasons
  - sample_formats 
  - sample_locations
  - sample_outcomes 
  - sample_temperatures
  - sample_types 
  - screening_data
  - sections 
  - subject_relationships 
  - subject_types
  - tracing_statuses 
  - units 
  - vital_statuses

#	only editors and above can read, create, edit or destroy
editor_resources:
  - abstracts 
  - candidate_controls 
  - contacts 
  - guides 
  - interviews 
  - patients

#	readers can read
#	editors and above can create, edit 
#	administrators and above can destroy
crud_resources:
  - addressings 
  - addresses 
  - consents 
  - documents 
  - enrollments 
  - home_exposures 
  - notes 
  - phone_numbers 
  - projects 
  - samples 
  - sample_transfers
  - study_subjects
