-
  :attributes:
  - :response_classification_day_7
  - :response_classification_day_14
  - :response_classification_day_28
  :length:
    :maximum: 2
  :allow_blank: true

-
  :attributes:
  - :cytogen_chromosome_number
  :length:
    :maximum: 3
  :allow_blank: true

-
  :attributes:
  - :flow_cyto_other_marker_1
  - :flow_cyto_other_marker_2
  - :flow_cyto_other_marker_3
  - :flow_cyto_other_marker_5
  - :response_other1_value_day_7
  - :response_other1_value_day_14
  - :response_other2_value_day_7
  - :response_other2_value_day_14
  - :response_other3_value_day_14
  - :response_other4_value_day_14
  - :response_other5_value_day_14
  :length:
    :maximum: 4
  :allow_blank: true

-
  :attributes:
  - :flow_cyto_other_marker_4
  - :is_karyotype_normal
  - :physical_neuro
  - :physical_other_soft_2
  - :physical_gingival
  - :physical_leukemic_skin
  - :physical_lymph
  - :physical_spleen
  - :physical_testicle
  - :physical_other_soft
  - :is_hypodiploid
  - :is_hyperdiploid
  - :is_diploid
  - :dna_index
  :length:
    :maximum: 5 
  :allow_blank: true

-
  :attributes:
  - :response_cd10_day_7
  - :response_cd10_day_14
  - :response_cd13_day_14
  - :response_cd13_day_7
  - :response_cd14_day_14
  - :response_cd14_day_7
  - :response_cd15_day_14
  - :response_cd15_day_7
  - :response_cd19_day_14
  - :response_cd19_day_7
  - :response_cd19cd10_day_14
  - :response_cd19cd10_day_7
  - :response_cd1a_day_14
  - :response_cd2a_day_14
  - :response_cd20_day_14
  - :response_cd20_day_7
  - :response_cd3a_day_14
  - :response_cd3_day_7
  - :response_cd33_day_14
  - :response_cd33_day_7
  - :response_cd34_day_14
  - :response_cd34_day_7
  - :response_cd4a_day_14
  - :response_cd5a_day_14
  - :response_cd56_day_14
  - :response_cd61_day_14
  - :response_cd7a_day_14
  - :response_cd8a_day_14
  - :flow_cyto_cd10
  - :flow_cyto_igm
  - :flow_cyto_bm_kappa
  - :flow_cyto_bm_lambda
  - :flow_cyto_cd10_19
  - :flow_cyto_cd19
  - :flow_cyto_cd20
  - :flow_cyto_cd21
  - :flow_cyto_cd22
  - :flow_cyto_cd23
  - :flow_cyto_cd24
  - :flow_cyto_cd40
  - :flow_cyto_surface_ig
  - :flow_cyto_cd1a
  - :flow_cyto_cd2
  - :flow_cyto_cd3
  - :flow_cyto_cd4
  - :flow_cyto_cd5
  - :flow_cyto_cd7
  - :flow_cyto_cd8
  - :flow_cyto_cd3_cd4
  - :flow_cyto_cd3_cd8
  - :flow_cyto_cd11b
  - :flow_cyto_cd11c
  - :flow_cyto_cd13
  - :flow_cyto_cd15
  - :flow_cyto_cd33
  - :flow_cyto_cd41
  - :flow_cyto_cdw65
  - :flow_cyto_cd34
  - :flow_cyto_cd61
  - :flow_cyto_cd14
  - :flow_cyto_glycoa
  - :flow_cyto_cd16
  - :flow_cyto_cd56
  - :flow_cyto_cd57
  - :flow_cyto_cd9
  - :flow_cyto_cd25
  - :flow_cyto_cd38
  - :flow_cyto_cd45
  - :flow_cyto_cd71
  - :flow_cyto_tdt
  - :flow_cyto_hladr
  - :response_hladr_day_7
  - :response_hladr_day_14
  - :response_tdt_day_7
  - :response_tdt_day_14
  :length:
    :maximum: 10 
  :allow_blank: true

-
  :attributes:
  - :response_blasts_units_day_7
  - :response_blasts_units_day_14
  - :response_blasts_units_day_28
  - :other_dna_measure
  - :response_fab_subtype
  :length:
    :maximum: 15 
  :allow_blank: true

-
  :attributes:
  - :flow_cyto_other_marker_1_name
  - :flow_cyto_other_marker_2_name
  - :flow_cyto_other_marker_3_name
  - :flow_cyto_other_marker_4_name
  - :flow_cyto_other_marker_5_name
  :length:
    :maximum: 20 
  :allow_blank: true

-
  :attributes:
  - :response_other1_name_day_7
  - :response_other1_name_day_14
  - :response_other2_name_day_7
  - :response_other2_name_day_14
  - :response_other3_name_day_14
  - :response_other4_name_day_14
  - :response_other5_name_day_14
  :length:
    :maximum: 25 
  :allow_blank: true

-
  :attributes:
  - :cytogen_other_trans_1
  - :cytogen_other_trans_2
  - :cytogen_other_trans_3
  - :cytogen_other_trans_4
  - :cytogen_other_trans_5
  - :cytogen_other_trans_6
  - :cytogen_other_trans_7
  - :cytogen_other_trans_8
  - :cytogen_other_trans_9
  - :cytogen_other_trans_10
  :length:
    :maximum: 35 
  :allow_blank: true

-
  :attributes:
  - :flow_cyto_igm_text
  - :flow_cyto_bm_kappa_text
  - :flow_cyto_bm_lambda_text
  - :flow_cyto_cd10_19_text
  - :flow_cyto_cd10_text
  - :flow_cyto_cd19_text
  - :flow_cyto_cd20_text
  - :flow_cyto_cd21_text
  - :flow_cyto_cd22_text
  - :flow_cyto_cd23_text
  - :flow_cyto_cd24_text
  - :flow_cyto_cd40_text
  - :flow_cyto_surface_ig_text
  - :flow_cyto_cd1a_text
  - :flow_cyto_cd2_text
  - :flow_cyto_cd3_text
  - :flow_cyto_cd4_text
  - :flow_cyto_cd5_text
  - :flow_cyto_cd7_text
  - :flow_cyto_cd8_text
  - :flow_cyto_cd3_cd4_text
  - :flow_cyto_cd3_cd8_text
  - :flow_cyto_cd11b_text
  - :flow_cyto_cd11c_text
  - :flow_cyto_cd13_text
  - :flow_cyto_cd15_text
  - :flow_cyto_cd33_text
  - :flow_cyto_cd41_text
  - :flow_cyto_cdw65_text
  - :flow_cyto_cd34_text
  - :flow_cyto_cd61_text
  - :flow_cyto_cd14_text
  - :flow_cyto_glycoa_text
  - :flow_cyto_cd16_text
  - :flow_cyto_cd56_text
  - :flow_cyto_cd57_text
  - :flow_cyto_cd9_text
  - :flow_cyto_cd25_text
  - :flow_cyto_cd38_text
  - :flow_cyto_cd45_text
  - :flow_cyto_cd71_text
  - :flow_cyto_tdt_text
  - :flow_cyto_hladr_text
  - :flow_cyto_other_marker_1_text
  - :flow_cyto_other_marker_2_text
  - :flow_cyto_other_marker_3_text
  - :flow_cyto_other_marker_4_text
  - :flow_cyto_other_marker_5_text
  - :ucb_fish_results
  - :fab_classification
  - :diagnosis_icdo_number
  - :diagnosis_is_other
  :length:
    :maximum: 50 
  :allow_blank: true

-
  :attributes:
  - :diagnosis_icdo_description
  :length:
    :maximum: 55 
  :allow_blank: true

-
  :attributes:
  - :ploidy_comment
  :length:
    :maximum: 100 
  :allow_blank: true

-
  :attributes:
  - :csf_red_blood_count_text
  - :chemo_protocol_name
  - :hyperdiploidy_by
  :length:
    :maximum: 250 
  :allow_blank: true

-
  :attributes:
  - :marrow_biopsy_diagnosis
  - :marrow_aspirate_diagnosis
  - :csf_white_blood_count_text
  - :csf_comment
  - :chemo_protocol_agent_description
  - :chest_imaging_comment
  - :cytogen_comment
  - :discharge_summary
  - :flow_cyto_remarks
  - :response_comment_day_7
  - :response_comment_day_14
  - :histo_report_results
  - :response_comment
  - :conventional_karyotype_results
  - :hospital_fish_results
  :length:
    :maximum: 65000 
  :allow_blank: true

-
  :attributes:
  - :histo_report_found
  - :cbc_report_found
  - :cerebrospinal_fluid_report_found
  - :chemo_protocol_report_found
  - :chest_ct_medmass_present
  - :chest_imaging_report_found
  - :cytogen_hospital_fish_done
  - :cytogen_inv16
  - :cytogen_is_hyperdiploidy
  - :cytogen_karyotype_done
  - :cytogen_report_found
  - :cytogen_t119
  - :cytogen_t1221
  - :cytogen_t821
  - :cytogen_t1517
  - :cytogen_t922
  - :cytogen_trisomy4
  - :cytogen_trisomy5
  - :cytogen_trisomy10
  - :cytogen_trisomy17
  - :cytogen_trisomy21
  - :cytogen_ucb_fish_done
  - :diagnosis_is_all
  - :diagnosis_is_aml
  - :diagnosis_is_b_all
  - :diagnosis_is_cll
  - :diagnosis_is_cml
#  - :diagnosis_is_other
  - :diagnosis_is_t_all
  - :discharge_summary_found
  - :flow_cyto_num_results_available
  - :flow_cyto_report_found
  - :h_and_p_reports_found
  - :hepatomegaly_present
  - :is_down_syndrome_phenotype
  - :is_cytogen_hosp_fish_t1221_done
  - :marrow_aspirate_report_found
  - :marrow_biopsy_report_found
  - :mediastinal_mass_present
  - :normal_cytogen
  - :patient_on_chemo_protocol
  - :ploidy_report_found
  - :received_bone_marrow_aspirate
  - :received_bone_marrow_biopsy
  - :received_cbc
  - :received_chemo_protocol
  - :received_chest_ct
  - :received_chest_xray
  - :received_csf
  - :received_cytogenetics
  - :received_discharge_summary
  - :received_flow_cytometry
  - :received_hla_typing
  - :received_h_and_p
  - :received_other_reports
  - :received_ploidy
  - :received_resp_to_therapy
  - :response_day14or28_flag
  - :response_day30_is_in_remission
  - :response_is_inconclusive_day_7
  - :response_is_inconclusive_day_14
  - :response_is_inconclusive_day_21
  - :response_is_inconclusive_day_28
  - :response_report_found_day_7
  - :response_report_found_day_14
  - :response_report_found_day_28
  - :splenomegaly_present
  - :tdt_often_found_flow_cytometry
  - :tdt_report_found
  - :blasts_are_present
  - :peripheral_blood_in_csf
  :inclusion:
    :in: <%= YNDK.valid_values %>
  :allow_nil: true

-
  :attributes:
  - :tdt_positive_or_negative
  :inclusion:
    :in: <%= POSNEG.valid_values %>
  :allow_nil: true


#
#	Add this for all integers that AREN'T YNDK, YNODK, ...
#
-
  :attributes:
#  - :abstract_version_id
  - :abstractor_id
  - :att13
#  - :blasts_are_present		#	YNDK
  - :bm1d_14_int
  - :bm1d_28_int
#  - :cbc_percent_blasts_unknown	#	boolean
#  - :cbc_report_found		#	YNDK
  - :cbf6b
  - :cd5_7
#  - :cerebrospinal_fluid_report_found		#	YNDK
#  - :chemo_protocol_report_found		#	YNDK
#  - :chest_ct_medmass_present		#	YNDK
#  - :chest_imaging_report_found		#	YNDK
  - :csf_red_blood_count
  - :cy_chrom01
  - :cy_chrom02
  - :cy_compkary
  - :cy_compkaryb
  - :cy_deletion
  - :cy_diag_conv
  - :cy_diag_fish
  - :cy_metaphase01
  - :cy_metaphase02
  - :cy_tri10_fish
  - :cy_tri17_fish
  - :cy_tri21_fish
  - :cy_tri21_pheno_old
  - :cy_tri4_fish
  - :cy_tri5_fish
#  - :cytogen_hospital_fish_done		#	YNDK
#  - :cytogen_inv16		#	YNDK
#  - :cytogen_is_hyperdiploidy		#	YNDK
#  - :cytogen_karyotype_done		#	YNDK
#  - :cytogen_report_found		#	YNDK
#  - :cytogen_t119		#	YNDK
#  - :cytogen_t1221		#	YNDK
#  - :cytogen_t1517		#	YNDK
#  - :cytogen_t821		#	YNDK
#  - :cytogen_t922		#	YNDK
#  - :cytogen_trisomy10		#	YNDK
#  - :cytogen_trisomy17		#	YNDK
#  - :cytogen_trisomy21		#	YNDK
#  - :cytogen_trisomy4		#	YNDK
#  - :cytogen_trisomy5		#	YNDK
#  - :cytogen_ucb_fish_done		#	YNDK
  - :diagnosis_all_type_id
  - :diagnosis_aml_type_id
#  - :diagnosis_is_all		#	YNDK
#  - :diagnosis_is_aml		#	YNDK
#  - :diagnosis_is_b_all		#	YNDK
#  - :diagnosis_is_cll		#	YNDK
#  - :diagnosis_is_cml		#	YNDK
#  - :diagnosis_is_other		#	YNDK
#  - :diagnosis_is_t_all		#	YNDK
#  - :discharge_summary_found		#	YNDK
  - :dischargesummaryfound
  - :fabclass
#  - :flow_cyto_num_results_available		#	YNDK
#  - :flow_cyto_report_found		#	YNDK
#  - :h_and_p_reports_found		#	YNDK
#  - :hepatomegaly_present		#	YNDK
#  - :histo_report_found		#	YNDK
  - :icdocodeid_1990
  - :icdocodeid_2000
#  - :id
#  - :is_cytogen_hosp_fish_t1221_done		#	YNDK
#  - :is_down_syndrome_phenotype		#	YNDK
#  - :is_h_and_p_report_found	#	boolean
#  - :is_verification_complete	#	boolean
#  - :marrow_aspirate_report_found		#	YNDK
#  - :marrow_biopsy_report_found		#	YNDK
#  - :mediastinal_mass_present		#	YNDK
#  - :normal_cytogen		#	YNDK
  - :number_metaphase_tested_karyotype
  - :number_normal_metaphase_karyotype
  - :number_of_blasts
#  - :patient_on_chemo_protocol		#	YNDK
  - :pe13
  - :pe7
#  - :peripheral_blood_in_csf		#	YNDK
#  - :ploidy_report_found		#	YNDK
#  - :received_bone_marrow_aspirate		#	YNDK
#  - :received_bone_marrow_biopsy		#	YNDK
#  - :received_cbc		#	YNDK
#  - :received_chemo_protocol		#	YNDK
#  - :received_chest_ct		#	YNDK
#  - :received_chest_xray		#	YNDK
#  - :received_csf		#	YNDK
#  - :received_cytogenetics		#	YNDK
#  - :received_discharge_summary		#	YNDK
  - :received_flow_cyto_day_14
  - :received_flow_cyto_day_7
#  - :received_flow_cytometry		#	YNDK
#  - :received_h_and_p		#	YNDK
#  - :received_hla_typing		#	YNDK
#  - :received_other_reports		#	YNDK
#  - :received_ploidy		#	YNDK
#  - :received_resp_to_therapy		#	YNDK
  - :response_blasts_day_14
  - :response_blasts_day_28
  - :response_blasts_day_7
#  - :response_day14or28_flag		#	YNDK
#  - :response_day30_is_in_remission		#	YNDK
  - :response_day_14_days_since_diagnosis
  - :response_day_14_days_since_treatment_began
  - :response_day_28_days_since_diagnosis
  - :response_day_28_days_since_treatment_began
  - :response_day_7_days_since_diagnosis
  - :response_day_7_days_since_treatment_began
  - :response_in_remission_day_14
#  - :response_is_inconclusive_day_14		#	YNDK
#  - :response_is_inconclusive_day_21		#	YNDK
#  - :response_is_inconclusive_day_28		#	YNDK
#  - :response_is_inconclusive_day_7		#	YNDK
  - :response_marrow_kappa_day_14
  - :response_marrow_kappa_day_7
  - :response_marrow_lambda_day_14
  - :response_marrow_lambda_day_7
#  - :response_report_found_day_14		#	YNDK
#  - :response_report_found_day_28		#	YNDK
#  - :response_report_found_day_7		#	YNDK
  - :reviewer_id
#  - :splenomegaly_present		#	YNDK
#  - :study_subject_id
  - :sty3g1
  - :sty3h1
  - :sty3i1
  - :sty3l1
  - :sty3m1
  - :sty3n1
  - :sty3o1
  - :sty3p1
  - :sty3q1
  - :sty3r1
#  - :tdt_found_in_flow_cyto_chart	#	boolean
#  - :tdt_found_in_separate_report	#	boolean
  - :tdt_numerical_result
#  - :tdt_often_found_flow_cytometry		#	YNDK
#  - :tdt_positive_or_negative	#	POSNEG
#  - :tdt_report_found		#	YNDK
  - :verified
#  - :vital_status_code
  :numericality: 
    :only_integer: true
  :allow_blank: true


