-
  :attribute: :notes
  :length:
    :maximum: 65000
  :allow_blank: true

-
  :attribute: :data_source_id
  :presence: true

-
  :attribute: :data_source
  :presence: true
  :if: :data_source_id

-
  :attribute: :other_data_source
  :presence: true
  :if: :data_source_is_other?

-
  :attributes:
  - :current_address
  - :address_at_diagnosis
  :inclusion:
    :in: <%= YNDK.valid_values %>
  :allow_nil: true


#-
#  :attribute: :data_source
#  :presence: true
#  :inclusion:
#    :in: <%= Addressing.valid_data_sources %>
#
