#-
#  :presence: true
#  :attributes: :address
#  :if: :address_id
-
  :presence: true
  :attributes: :instrument_version
  :if: :instrument_version_id
-
  :presence: true
  :attributes: :interview_method
  :if: :interview_method_id
-
  :presence: true
  :attributes: :interviewer
  :if: :interviewer_id
-
  :presence: true
  :attributes: :language
  :if: :language_id
-
  :presence: true
  :attributes: :study_subject
  :if: :study_subject_id
-
  :presence: 
    :message: "You must specify a relationship with 'other relationship' is selected"
  :attributes: :other_subject_relationship
  :if: :subject_relationship_is_other?
-
  :absence:
    :message: "Other Subject Relationship not allowed"
  :attributes: :other_subject_relationship
  :if: :subject_relationship_id_blank?
-
  :length:
    :maximum: 250
  :attributes:
  - :other_subject_relationship
  - :respondent_first_name
  - :respondent_last_name
  :allow_blank: true
-
  :attributes:
  - :began_at
  - :ended_at
  - :intro_letter_sent_on
  :complete_date: true
  :allow_nil: true
